# Generated by Django 5.1.6 on 2025-02-17 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_Order',
            fields=[
                ('order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('totalAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orderManagement.c_order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prepTime', models.DateTimeField(auto_now_add=True)),
                ('category_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='orderManagement.product_category')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Line',
            fields=[
                ('orderLine_ID', models.AutoField(primary_key=True, serialize=False)),
                ('product_quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='orderManagement.c_order')),
                ('product_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderManagement.product_category')),
            ],
        ),
    ]
