# Generated by Django 5.1.6 on 2025-03-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0002_alter_product_preptime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='description',
        ),
    ]
