# Generated by Django 5.1.6 on 2025-03-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0003_remove_product_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_order',
            name='customer_name',
            field=models.CharField(default="Customer's Name", max_length=50),
        ),
    ]
