# Generated by Django 5.1.6 on 2025-03-18 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0004_c_order_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_order',
            name='customer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order_line',
            name='product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orderManagement.product'),
        ),
    ]
