# Generated by Django 5.1.6 on 2025-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0005_alter_c_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/banana.svg', upload_to='products/'),
        ),
    ]
