# Generated by Django 5.1.6 on 2025-03-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0006_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prepTime',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='banana.svg', upload_to='products/'),
        ),
    ]
