# Generated by Django 5.1.6 on 2025-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderManagement', '0007_remove_product_preptime_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
