# Generated by Django 5.1.6 on 2025-02-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corder',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('totalAmount', models.IntegerField(max_length=30)),
            ],
        ),
    ]
